# -*- encoding: utf-8 -*-

{
    'name': u'Tableaux à saisie manuelle de la liasse fiscale Marocaine',
    'version': '1.0',
    'author': 'Osisoftware',
    'website': 'http://www.osisoftware.ma',
    "depends": [
        'date_range','odoo_excel_engin','immobilisation'
    ],
    'data': [
        
        "views/credit_bail_view.xml",
        "views/bilan_actif.xml",
        "views/bilan_passif.xml",
        "views/cpc_1.xml",
        "views/cpc_2.xml",
        "views/esg_tfr.xml",
        "views/esg_caf.xml",
        "views/detail_cpc.xml",
        "views/provisions_view.xml",
        "views/titre_participation_view.xml",
        "views/repartition_capital_social_view.xml",
        "views/affectation_resultats_intervenue_view.xml",
        "views/plus_values_fusion_view.xml",
        "views/interets_emprunts_view.xml",
        "views/locations_baux_view.xml",
        "views/detail_stock_view.xml",
        "views/calcul_impot.xml",
        "views/tva.xml",
        "views/passage.xml",
        "views/finance_part_1.xml",
        "views/finance_part_2.xml",
        "views/datation.xml",
        "views/evaluation.xml",
        "views/derogation.xml",
        "views/changement.xml",
        "views/suretes.xml",
        "views/engagement.xml",
        "views/non_valeur.xml",
        "views/immo_menus.xml",
        "views/control_table.xml",
        "views/resultats.xml",
        "views/full_reconcile.xml",
        "wizards/journal_export.xml",
        "security/liasse_fiscale_tables.xml",
        "security/ir.model.access.csv",
        ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
